name: stts_example
description: "Demonstrates how to use the stts plugin."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  stts: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
