name: stts_platform_interface
description: A common interface for the stts package to call dedicated platforms with method channel.
homepage: https://github.com/llfbandit/stts/tree/master/stts_platform_interface
version: 0.9.2

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^5.0.0