name: stts_web
description: Web specific implementation for stts package called by stts_platform_interface.
version: 0.9.3
homepage: https://github.com/llfbandit/stts/tree/master/stts_web

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  stts_platform_interface: ^0.9.3
  web: ^1.0.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SttsWeb
        fileName: stts_web.dart
